# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Array-Iterator
version:      0.06
version_from: lib/Array/Iterator.pm
installdirs:  site
requires:
    Test::Exception:               0.15
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
